START TRANSACTION;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|blinding_lights|The Weeknd'), 1.1, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'The Weeknd', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Ed Sheeran', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Harry Styles', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Post Malone', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|shape_of_you|Ed Sheeran'), 1.0, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Ed Sheeran', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Shawn Mendes', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Justin Bieber', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Lewis Capaldi', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|levitating|Dua Lipa'), 1.2, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Dua Lipa', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Ava Max', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Zara Larsson', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Ellie Goulding', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|drivers_license|Olivia Rodrigo'), 1.3, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Olivia Rodrigo', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Sabrina Carpenter', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Billie Eilish', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Tate McRae', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|bad_guy|Billie Eilish'), 1.1, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Billie Eilish', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Lorde', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Halsey', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Olivia Rodrigo', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|sorry|Justin Bieber'), 1.1, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Justin Bieber', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Shawn Mendes', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'The Weeknd', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Harry Styles', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|dance_monkey|Tones and I'), 1.4, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Tones and I', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Sia', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Daya', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'LP', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|someone_you_loved|Lewis Capaldi'), 1.2, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Lewis Capaldi', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Tom Walker', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'James Arthur', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Sam Smith', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|flowers|Miley Cyrus'), 1.0, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Miley Cyrus', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Dua Lipa', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Selena Gomez', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Ariana Grande', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|as_it_was|Harry Styles'), 1.1, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Harry Styles', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Niall Horan', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Louis Tomlinson', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Shawn Mendes', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|dont_start_now|Dua Lipa'), 1.1, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Dua Lipa', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Bebe Rexha', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Anne-Marie', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Ava Max', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|roar|Katy Perry'), 1.0, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Katy Perry', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Pink', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Kesha', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Lady Gaga', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|rolling_in_the_deep|Adele'), 1.1, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Adele', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Duffy', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Emeli Sande', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Leona Lewis', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|someone_like_you|Adele'), 1.1, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Adele', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Sam Smith', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Jessie J', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Sia', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|cheap_thrills|Sia'), 1.3, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Sia', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Zara Larsson', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Bebe Rexha', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Anne-Marie', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|waka_waka|Shakira'), 1.1, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Shakira', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Jennifer Lopez', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Gloria Estefan', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Karol G', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|despacito|Luis Fonsi'), 1.1, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Luis Fonsi', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Daddy Yankee', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'J Balvin', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Maluma', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|mi_gente|J Balvin'), 1.3, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'J Balvin', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Maluma', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Ozuna', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Bad Bunny', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|hawai|Maluma'), 1.4, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Maluma', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'J Balvin', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Sebastian Yatra', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Luis Fonsi', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|pepas|Farruko'), 1.5, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Farruko', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Bad Bunny', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Ozuna', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Anuel AA', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|danza_kuduro|Don Omar'), 1.3, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Don Omar', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Daddy Yankee', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'J Balvin', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Nicky Jam', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|con_calma|Daddy Yankee'), 1.4, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Daddy Yankee', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Don Omar', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Nicky Jam', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Bad Bunny', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|montero|Lil Nas X'), 1.3, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Lil Nas X', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Post Malone', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Travis Scott', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Doja Cat', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|rockstar|Post Malone'), 1.2, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Post Malone', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Drake', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'The Weeknd', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Future', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|gods_plan|Drake'), 1.2, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Drake', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Travis Scott', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Post Malone', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Future', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|industry_baby|Lil Nas X'), 1.4, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Lil Nas X', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Jack Harlow', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Drake', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Central Cee', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|without_me|Halsey'), 1.4, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Halsey', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Billie Eilish', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Lorde', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Dua Lipa', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|stitches|Shawn Mendes'), 1.2, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Shawn Mendes', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Justin Bieber', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Charlie Puth', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Niall Horan', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|believer|Imagine Dragons'), 1.1, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Imagine Dragons', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'OneRepublic', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Bastille', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Coldplay', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|thunder|Imagine Dragons'), 1.2, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Imagine Dragons', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'OneRepublic', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'The Killers', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Coldplay', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|radioactive|Imagine Dragons'), 1.2, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Imagine Dragons', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Linkin Park', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Fall Out Boy', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Bastille', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|take_me_to_church|Hozier'), 1.4, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Hozier', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'George Ezra', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'James Bay', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Sam Smith', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|human|RagnBone Man'), 1.5, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'RagnBone Man', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Tom Walker', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'George Ezra', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'James Arthur', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|we_found_love|Rihanna'), 1.1, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Rihanna', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Beyonce', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Nicki Minaj', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Katy Perry', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|diamonds|Rihanna'), 1.2, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Rihanna', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Beyonce', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Alicia Keys', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Katy Perry', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|call_me_maybe|Carly Rae Jepsen'), 1.3, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Carly Rae Jepsen', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Selena Gomez', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Demi Lovato', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Ariana Grande', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|sinceramente|Annalisa'), 1.4, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Annalisa', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Elodie', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Emma', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Alessandra Amoroso', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|tuta_gold|Mahmood'), 1.4, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Mahmood', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Lazza', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Blanco', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Tedua', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|la_noia|Angelina Mango'), 1.5, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Angelina Mango', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Annalisa', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Elodie', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Emma', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|occidentalis_karma|Francesco Gabbani'), 1.3, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Francesco Gabbani', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Marco Mengoni', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Mahmood', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Fabrizio Moro', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|soldi|Mahmood'), 1.2, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Mahmood', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Blanco', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Marco Mengoni', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Sangiovanni', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|due_vite|Marco Mengoni'), 1.3, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Marco Mengoni', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Tiziano Ferro', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Mahmood', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Ultimo', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|musica_leggerissima|Colapesce Dimartino'), 1.6, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Colapesce Dimartino', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'The Kolors', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Pinguini Tattici Nucleari', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Coma Cose', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|supereroi|Mr Rain'), 1.5, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Mr Rain', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Rkomi', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Irama', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Tananai', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|cenere|Lazza'), 1.4, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Lazza', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Geolier', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Sfera Ebbasta', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Tony Effe', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|mon_amour|Annalisa'), 1.3, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Annalisa', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Noemi', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Elodie', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Emma', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|italodisco|The Kolors'), 1.5, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'The Kolors', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Coma Cose', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Pinguini Tattici Nucleari', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Boomdabash', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|brividi|Mahmood e Blanco'), 1.6, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Mahmood e Blanco', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Mahmood', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Blanco', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Mr Rain', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|espresso|Sabrina Carpenter'), 1.4, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Sabrina Carpenter', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Olivia Rodrigo', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Ariana Grande', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Tate McRae', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
INSERT INTO domande (testo, codice_domanda, fingerprint_unico, difficolta, tipo_domanda, modalita_party, fase_domanda, media_image_path, media_audio_path, media_audio_preview_sec, media_caption, config_json, argomento_id, attiva) VALUES ('Chi canta questo brano?', NULL, SHA1('srb|a6|greedy|Tate McRae'), 1.5, 'SARABANDA', NULL, 'intro', NULL, NULL, 5, NULL, NULL, 6, 1);
SET @d_id = LAST_INSERT_ID();
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Tate McRae', 1);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Dua Lipa', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Ava Max', 0);
INSERT INTO opzioni (domanda_id, testo, corretta) VALUES (@d_id, 'Zara Larsson', 0);
UPDATE domande SET codice_domanda = CONCAT('SRB-A006-', LPAD(@d_id, 5, '0')) WHERE id = @d_id;
COMMIT;
